// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSqgNvIVaip5eBP4dCA7_GYmyjRSiM_Sc',
    appId: '1:285656534014:web:54f008e9187538664f8eaf',
    messagingSenderId: '285656534014',
    projectId: 'app-expense-flutter',
    authDomain: 'app-expense-flutter.firebaseapp.com',
    storageBucket: 'app-expense-flutter.appspot.com',
    measurementId: 'G-C0799YYL2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR3h6ALf8ImsIu9ZsQKkpe_joL-CNyqj8',
    appId: '1:285656534014:android:eef116915a3bc3734f8eaf',
    messagingSenderId: '285656534014',
    projectId: 'app-expense-flutter',
    storageBucket: 'app-expense-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD33GrIB_dvsoHy0f5F_D92nONljCHi8AE',
    appId: '1:285656534014:ios:8dcefa672f3a844a4f8eaf',
    messagingSenderId: '285656534014',
    projectId: 'app-expense-flutter',
    storageBucket: 'app-expense-flutter.appspot.com',
    iosBundleId: 'com.example.appexppense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD33GrIB_dvsoHy0f5F_D92nONljCHi8AE',
    appId: '1:285656534014:ios:feebb35cb1c3a2e94f8eaf',
    messagingSenderId: '285656534014',
    projectId: 'app-expense-flutter',
    storageBucket: 'app-expense-flutter.appspot.com',
    iosBundleId: 'com.example.appexppense.RunnerTests',
  );
}
